### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference

### ISSUE THREAD

**Issue by AkashDaga** [razorpay/razorpay-android-sample-app#95] opened 2019-02-05 04:36 UTC
**Guys I dont know how to reproduce it but some of our users are facing this issue, this is the stack trace I got from Crashlytics, Please have a look into this**
com.razorpay.l__d$.backPressed (Unknown Source)
com.razorpay.r_$Z$.backPressed (Unknown Source)
com.razorpay.b__J_.onBackPressed (Unknown Source)
com.razorpay.CheckoutActivity.onBackPressed (Unknown Source)
android.app.Activity.onKeyUp (Activity.java:2530)
android.view.KeyEvent.dispatch (KeyEvent.java:2762)
android.app.Activity.dispatchKeyEvent (Activity.java:2783)
com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent (PhoneWindow.java:2380)
android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent (ViewRootImpl.java:4655)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4611)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4106)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4159)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4125)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4289)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4133)
android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4346)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4106)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4159)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4125)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4133)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4106)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4159)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4125)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4322)
android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent (ViewRootImpl.java:4492)
android.view.inputmethod.InputMethodManager$PendingEvent.run (InputMethodManager.java:2330)
android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback (InputMethodManager.java:1934)
android.view.inputmethod.InputMethodManager.finishedInputEvent (InputMethodManager.java:1925)
android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished (InputMethodManager.java:2307)
android.view.InputEventSender.dispatchInputEventFinished (InputEventSender.java:141)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:328)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:5776)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:789)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:679)

**Comment by AkashDaga** [comment] 2019-02-05 07:32
**React Native library version:** "react-native-razorpay": "^2.0.16",

**Device Info:**
Brand: LENOVO
Model: Lenovo VIBE X3 Lite
Orientation: Portrait
RAM free: 499.77 MB
Disk free: 1.14 GB

**Operating System**
Version: 6.0
Orientation: Portrait
Rooted: No

**Comment by debugger22** [comment] 2019-02-08 13:07
We're also facing this issue. Unable to reproduce. 

**SDK** com.razorpay:checkout:1.5.1

It's happening on all devices and all OS versions.

**Comment by lastw0nd3r** [comment] 2019-02-14 07:32
Same is the case with us, we have raised it over email multiple times. Happening to our users as well.

**Comment by lastw0nd3r** [comment] 2019-02-15 06:49
@sumedht Happening on Android to random set of users, we're on version - 'com.razorpay:checkout:1.5.2'

**Comment by umanghome** [comment] 2019-02-22 14:10
@akashdaga @lastw0nd3r @debugger22 - Would any of you be willing to send your app to us? We are unable to reproduce this.

**Comment by donpeter06** [comment] 2019-02-24 06:55
The crash occurred to our Android users
Native Android App

Razor pay - com.razorpay:checkout:1.5.2
Android - 8.1.0
Device -  Xiaomi Redmi Note 6 Pro

**Comment by AkashDaga** [comment] 2019-02-24 07:01
@umanghome I can give you our testing app but it's not reproducible some times users are facing this issue, but we are not able to reproduce this

**Comment by AkashDaga** [comment] 2019-02-25 12:30
@umanghome 
**Today also we got this issue, I am posting the stack trace see if you can get something from it**

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
       at com.razorpay.l__d$.backPressed(Unknown Source:16)
       at com.razorpay.r_$Z$.backPressed(Unknown Source:52)
       at com.razorpay.b__J_.onBackPressed(Unknown Source:7)
       at com.razorpay.CheckoutActivity.onBackPressed(Unknown Source)
       at android.app.Activity.onKeyUp(Activity.java:3086)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2737)
       at android.app.Activity.dispatchKeyEvent(Activity.java:3369)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:377)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5081)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4949)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4470)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4523)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4489)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4629)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4497)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4686)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4470)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4523)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4489)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4497)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4470)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4523)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4489)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4662)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4823)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:6912)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

**Comment by sidx1024** [comment] 2019-02-26 13:08
@AkashDaga @lastw0nd3r @debugger22 We have released a new SDK which fixes this issue `com.razorpay:checkout:1.5.3`.

**Comment by sumedht** [comment] 2019-03-26 11:38
Closing this issue. Fixed in latest sdk version

**Closed by sumedht** 2019-03-26 11:38 UTC
