### ISSUE TITLE
Illegal argument exception it comes when we return from other wallet after successfull transaction and activityt will crashed.

### ISSUE THREAD

**Issue by arshi7852** [razorpay/razorpay-android-sample-app#275] opened 2021-12-02 11:55 UTC
## Description
i select product go for payment using razorpay then select pay by phonepe wallet paid successfully then come back to app. then the activity has been crashed and order not placed but payment deducted by account. this s occur many time.
This is very serious issue customer get irritated if payment is deducted from wallet and order not placed.

## Razorpay SDK Version :
    implementation 'com.razorpay:checkout:1.6.15'

## Android OS Version :
Android 11 (SDK 30)

### What you did:

checkout->pay by phonepe wallet->paid amnt->return to app ->activity crashed.
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. 
java.lang.RuntimeException: 
  at android.os.AsyncTask$4.done (AsyncTask.java:415)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:305)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:923)
Caused by: java.lang.IllegalArgumentException: 
  at android.app.LoadedApk.forgetServiceDispatcher (LoadedApk.java:1887)
  at android.app.ContextImpl.unbindService (ContextImpl.java:1954)
  at android.content.ContextWrapper.unbindService (ContextWrapper.java:810)
  at com.razorpay.a_$P$.a (AdvertisingIdUtil.java:47)
  at com.razorpay.a_$P$.doInBackground (AdvertisingIdUtil.java:25)
  at android.os.AsyncTask$3.call (AsyncTask.java:394)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:305)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:923)

2.
java.lang.RuntimeException: 
  at android.os.AsyncTask$4.done (AsyncTask.java:415)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:305)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:923)
Caused by: java.lang.IllegalArgumentException: 
  at android.app.LoadedApk.forgetServiceDispatcher (LoadedApk.java:1887)
  at android.app.ContextImpl.unbindService (ContextImpl.java:1954)
  at android.content.ContextWrapper.unbindService (ContextWrapper.java:810)
  at com.razorpay.AdvertisingIdUtil$AdvertisingIdAsyncTask.doInBackground (AdvertisingIdUtil.java:47)
  at com.razorpay.AdvertisingIdUtil$AdvertisingIdAsyncTask.doInBackground (AdvertisingIdUtil.java:25)
  at android.os.AsyncTask$3.call (AsyncTask.java:394)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:305)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:923)

**Comment by arshi7852** [comment] 2021-12-02 12:05
Plzzz solve this issue as soon as possible.
App is on live mode.

**Comment by Vicky19r** [comment] 2021-12-05 00:55
Facing the same issue, it would be better if you make it a standard step part of your release process to test thoroughly all types of payments once before releasing a new version on your website?

**Comment by arshi7852** [comment] 2021-12-06 03:17
ok but how to resolve this issue ??
@Vicky19r plzz give me some suggestion.

**Comment by Vicky19r** [comment] 2021-12-06 21:06
@arshi7852 i don't know how to fix this. This is the razorpay checkout library's issue. We can fix it without editing their library. Better not to upgrade to latest versions in the future immediately unless you are a big company and have resources to test it on all types of devices in all possible configurations.

**Comment by Vicky19r** [comment] 2021-12-06 21:17
@arshi7852 i guess it is something related to not setting exported=true/false property for the checkout activity in the manifest file that is coming from the razorpay checkout library. Even credit card payments are failing in some devices because of this. I am just guessing. Just create a new project with an empty activity and just add only razor pay checkout library 1.6.15 in the build.gradle file, trying starting the app and you will see the build failing with an error message about the exported property in the manifest file. 

This is very bad on razorpay side for not doing this basic testing before releasing a plugin.

**Comment by vivekshindhe** [comment] 2021-12-07 05:05
@arshi7852 Could you please send the payload that you are sending to the SDK? Regarding the exported=true/false property that is related to Android 12. And we are making a release for that.

**Comment by vivekshindhe** [comment] 2021-12-07 05:07
@arshi7852 Also, if this is affecting a lot of payments, you can reach out to Razorpay to temporarily disable wallets until we figure out why this is happening.

**Comment by Vicky19r** [comment] 2021-12-10 03:23
@vivekshindhe first i was on 1.5 something and things started failing, then i had to upgrade all my app so that i can upgrade razorpay plugin to 1.6.15 the latest specified on the site, and now you are saying for new devices we are making a new release. Is there any place where you specified which android versions are compatible with which razorpay checkout library versions?

**Comment by Vicky19r** [comment] 2021-12-12 03:42
@vivekshindhe we are getting bad feedback from our customers because your library is failing. How long do you think it will take to get this fixed? Also this time please test all types of payments on all popular old and new devices. Thanks.

**Comment by vivekshindhe** [comment] 2021-12-13 07:24
@Vicky19r Appreciate the feedback. Here's my take on it. I don't know why you are mixing two separate things. Support for android 12 has been a bit tricky on our end. Hence the time delay. Second, these issues are generally not reproducible by us. We haven't had this issue happen to us once. And hence the time to resolve it. The logs given by @arshi7852 do tell something and we have made corrections to that, but apart from that, if we cannot reproduce it I'm sure you know it's difficult for us to sort it as well. There are many external factors at play here as well. I'm sure if you test it on your device you won't see the error either. The razorpay account, device type, integration, error on/from the wallet. Also, for testing we obviously do test. But it is not possible or feasible to test on all devices with the latest android versions especially when the software of the device pertaining to that company also makes a play in how the OS works. We will keep this in mind. We will look for a solution, this is the state of things. And in android, we have to make releases everytime we update something. In essence as you said, we do not want to make a release every two days. Which also add to our timeline. Will try to expedite this.

**Comment by SumeetMoray** [comment] 2022-01-07 08:27
> @Vicky19r Appreciate the feedback. Here's my take on it. I don't know why you are mixing two separate things. Support for android 12 has been a bit tricky on our end. Hence the time delay. Second, these issues are generally not reproducible by us. We haven't had this issue happen to us once. And hence the time to resolve it. The logs given by @arshi7852 do tell something and we have made corrections to that, but apart from that, if we cannot reproduce it I'm sure you know it's difficult for us to sort it as well. There are many external factors at play here as well. I'm sure if you test it on your device you won't see the error either. The razorpay account, device type, integration, error on/from the wallet. Also, for testing we obviously do test. But it is not possible or feasible to test on all devices with the latest android versions especially when the software of the device pertaining to that company also makes a play in how the OS works. We will keep this in mind. We will look for a solution, this is the state of things. And in android, we have to make releases everytime we update something. In essence as you said, we do not want to make a release every two days. Which also add to our timeline. Will try to expedite this.

You say support for android 12 is quite tricky ... but adding just one tag "android:exported=false" into your manifest is all that is needed for us to use your library in android 12 ... 

Is this so much tricky ? Who are you fooling vivek !

**Comment by vivekshindhe** [comment] 2022-01-10 06:37
@SumeetMoray sirji, we do have other libraries to take care of too. I understand the problem here and we are resolving it. Never an intention to 'fool' anybody, rather, give a good experience. Thank you for your comment.

**Comment by SumeetMoray** [comment] 2022-01-10 06:46
> ... adding just one tag "android:exported=false" into your manifest is all that is needed for us to use your library in android 12 ...

@vivekshindhe have you tried this ? ... it takes less than a minute ... 

I have many (more than 50)  libraries as dependencies in the project ... and there is only one library which is showing this problem ... that is RazorPay ... What does that show ?

This issue is pending since 4-6 months ... RazorPay is a big Company ... this isnt the kind of attitude we expect from you guys !

**Comment by vivekshindhe** [comment] 2022-01-10 06:47
The release is coming up in a couple of days. We thank you for your patience on the matter.

**Comment by vivekshindhe** [comment] 2022-02-14 05:59
Hello everyone, the SDK has been updated. For support for android 32. Please update to version 1.6.17. Thank you. closing this ticket.

**Closed by vivekshindhe** 2022-02-14 05:59 UTC
