### ISSUE TITLE
 CheckoutBridge.sendAnalyticsData is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.12&library=checkoutjs&platform=android

### ISSUE THREAD

**Issue by bhupalreddykokkanti** [razorpay/razorpay-android-sample-app#136] opened 2019-12-13 13:25 UTC
Hi ,

I am facing this issue. When entering into the Checkout Page. Can any one help me on it

**Comment by sumedht** [comment] 2020-02-20 17:17
@bhupalreddykokkanti R u still facing this issue? Can u elaborate more on this?

**Comment by anilwarbhe** [comment] 2020-03-06 12:10
I am also facing the same issue:
03-06 17:24:52.244 15624 15624 I chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Invalid or unexpected token", source: https://api.razorpay.com/v1/checkout/public?version=1.5.12&library=checkoutjs&platform=android (1)
03-06 17:24:52.245 15624 15624 I chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: CheckoutBridge.sendAnalyticsData is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.12&library=checkoutjs&platform=android (1)
03-06 17:24:52.427   553   716 W SurfaceFlinger: Attempting to set client state on removed layer: com.test.razorpayapp/com.razorpay.CheckoutActivity#1

**Comment by sumedht** [comment] 2020-06-18 10:18
@anilwarbhe Wanted to know what is source of this. Does app crashing or behaving unexpectedly? or it's in log?

**Comment by souvikdas2411** [comment] 2020-07-14 18:23
In the log. Please help.

**Comment by souvikdas2411** [comment] 2020-07-14 18:23
> @anilwarbhe Wanted to know what is source of this. Does app crashing or behaving unexpectedly? or it's in log?

In the log. Please help.

**Comment by sumedht** [comment] 2020-08-18 02:45
@souvikdas2411 want more details like what exactly it causing. Does app crashing/behaving unexpectedly, version of SDK.

**Comment by mahendradabi** [comment] 2020-08-30 12:17
following error printed in logcat and screen apear blank not even able to back the screen need to kill the app and restart
2020-08-30 17:41:04.333 13017-13017/com.ahaar.india I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: CheckoutBridge.sendAnalyticsData is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.16&library=checkoutjs&platform=android (0)
2020-08-30 17:41:04.454 13017-13017/com.ahaar.india I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.16&library=checkoutjs&platform=android (0)

**Comment by vivekshindhe** [comment] 2020-08-31 05:40
@mahendradabi Thanks for reaching out to us. Could you please use our latest SDK 
> com.razorpay:checkout:1.6.3
Also, please cross verify the apiKeys once. Just for the sake of covering all bases. Let us know if the issue still persists.

**Comment by kamleshch86** [comment] 2020-09-20 15:02
In above case must sure that your app icon size should be maximum 512X512 px ......generally it raise this kind of problem...

**Comment by immohanravi** [comment] 2020-10-13 13:49
> In above case must sure that your app icon size should be maximum 512X512 px ......generally it raise this kind of problem...

Yeah this is the problem

**Comment by sumedht** [comment] 2020-10-21 07:03
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Closed by sumedht** 2020-10-21 07:03 UTC

**Comment by MayurDokras** [comment] 2022-03-19 17:18
> > In above case must sure that your app icon size should be maximum 512X512 px ......generally it raise this kind of problem...
> 
> Yeah this is the problem

what is the relevance of the app icon with this error? if you don't mind please explain

**Comment by vishwatejaaverager** [comment] 2023-11-05 09:19
i changed the app icon below 512px but still i am facing this problem any solution for this

**Comment by vivekshindhe** [comment] 2023-11-06 04:08
@vishwatejaaverager This is not a blocker for payment. It's an error thrown from the webview which will not hamper the process at all. We are looking into this from our end. Is your experience with the issue different? Is it blocking payment or not loading the checkout page?

**Comment by vishwatejaaverager** [comment] 2023-11-06 17:35
the payment screen is loading and then crashing again idk y its happening with this function

**Comment by vivekshindhe** [comment] 2023-11-06 17:38
@vishwatejaaverager Can you send the crash logs? Mostly it will not be related to this function. There should be a stacktrace available for you apart from this error. Itd be really helpful if you could send the logs over for us to reproduce the issue.

**Comment by vishwatejaaverager** [comment] 2023-11-06 17:47
/WebViewFactory(10220): Loading com.google.android.webview version 113.0.5672.136 (code 567263637)
2
W/ziparchive(10220): Unable to open '/data/app/~~XjnxVuVABpghu2TsSrXOPw==/com.google.android.trichromelibrary_567263637-JB3u6w5TPq3ru3_1UBbChQ==/TrichromeLibrary.dm': No such file or directory
W/om.leo.needmoto(10220): Entry not found
D/nativeloader(10220): Configuring clns-11 for other apk /data/app/~~XjnxVuVABpghu2TsSrXOPw==/com.google.android.trichromelibrary_567263637-JB3u6w5TPq3ru3_1UBbChQ==/TrichromeLibrary.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~gLj34l2dRidwmL9WlKfM0Q==/com.google.android.webview-4Qj2Xu6SO0CQH_FquOwGnA==/lib/x86_64:/data/app/~~gLj34l2dRidwmL9WlKfM0Q==/com.google.android.webview-4Qj2Xu6SO0CQH_FquOwGnA==/WebViewGoogle.apk!/lib/x86_64:/data/app/~~XjnxVuVABpghu2TsSrXOPw==/com.google.android.trichromelibrary_567263637-JB3u6w5TPq3ru3_1UBbChQ==/TrichromeLibrary.apk!/lib/x86_64, permitted_path=/data:/mnt/expand
D/nativeloader(10220): Configuring clns-12 for other apk /data/app/~~gLj34l2dRidwmL9WlKfM0Q==/com.google.android.webview-4Qj2Xu6SO0CQH_FquOwGnA==/WebViewGoogle.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~gLj34l2dRidwmL9WlKfM0Q==/com.google.android.webview-4Qj2Xu6SO0CQH_FquOwGnA==/lib/x86_64:/data/app/~~gLj34l2dRidwmL9WlKfM0Q==/com.google.android.webview-4Qj2Xu6SO0CQH_FquOwGnA==/WebViewGoogle.apk!/lib/x86_64:/data/app/~~XjnxVuVABpghu2TsSrXOPw==/com.google.android.trichromelibrary_567263637-JB3u6w5TPq3ru3_1UBbChQ==/TrichromeLibrary.apk!/lib/x86_64, permitted_path=/data:/mnt/expand
W/om.leo.needmoto(10220): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
W/om.leo.needmoto(10220): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
W/om.leo.needmoto(10220): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
W/om.leo.needmoto(10220): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/om.leo.needmoto(10220): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
I/cr_WVCFactoryProvider(10220): Loaded version=113.0.5672.136 minSdkVersion=29 isBundle=false multiprocess=true packageId=2
I/cr_VariationsUtils(10220): Failed reading seed file "/data/user/0/com.leo.needmoto/app_webview/variations_seed_new"
I/cr_VariationsUtils(10220): Failed reading seed file "/data/user/0/com.leo.needmoto/app_webview/variations_seed"
I/cr_VariationsUtils(10220): Requesting new seed from IVariationsSeedServer
I/cr_LibraryLoader(10220): Successfully loaded native library
I/cr_CachingUmaRecorder(10220): Flushed 8 samples from 8 histograms.
D/AutofillManager(10220): Fill dialog is enabled:false, hints=[password, passwordAuto, creditCardNumber, creditCardSecurityCode, creditCardExpirationDate]
E/chromium(10220): [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/com.leo.needmoto/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
E/chromium(10220): [ERROR:simple_index_file.cc(614)] Could not reconstruct index from disk
D/CompatibilityChangeReporter(10220): Compat change id reported: 214741472; UID 10194; state: ENABLED
D/AutofillManager(10220): Fill dialog is enabled:false, hints=[password, passwordAuto, creditCardNumber, creditCardSecurityCode, creditCardExpirationDate]

**Comment by vivekshindhe** [comment] 2023-11-07 04:42
@vishwatejaaverager From the logs I can see the error ``` Authentication failed``` with your test key. Can you confirm if the key you are using is correct? And if it is, please generate a new test key and test once? If this doesn't work as well, please raise a ticket on your dashboard. Once the issue with the key is resolved, it should start working.

**Comment by vishwatejaaverager** [comment] 2023-11-19 10:22
@vivekshindhe thank you will check and update you

**Comment by Sahil-Kundaliya** [comment] 2024-03-28 14:59
same issue !! 
E/com.razorpay.checkout(19060): Webview JS Error: Uncaught TypeError: CheckoutBridge.sendAnalyticsData is not a function
I/chromium(19060): [INFO:CONSOLE(1)] "Uncaught TypeError: CheckoutBridge.sendAnalyticsData is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.6.38&library=checkoutjs&platform=android&session_token=BB12611CE5AB3FED5AA889CAB10056F7F54E985771DB8521C85A51D2F731407AED66F9069FC2E7BD47957CF896D9AF389AAE299A0F817992D95A3DB8EB6108715D05D89DA86CC1237BAFE09CE8BCD210771E74AC4DE34D56BEC240415BCF2C9F8B7FFFE9C86BCBF0E6E4B27A134980B010BF3BC0F633CB40C0911516A8F2E55C39970B2114A54D04BE001FF4D7C2EDCC7EDE42&traffic_env=production (1)
I/chromium(19060): [INFO:CONSOLE(1)] "Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently", source: https://checkout-static-next.razorpay.com/build/6ce6bb144a8424e4c21d49c6c3751dace59be140/checkout-frame.modern.js (1)
I/ViewRootImpl@d533660[CheckoutActivity](19060): MSG_WINDOW_FOCUS_CHANGED 0 1
I/ViewRootImpl@3706fb6[MainActivity](19060): stopped(false) old=true
I/System.out(19060): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(19060): (HTTPLog)-Static: isSBSettingEnabled false
E/flutter (19060): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast
E/flutter (19060): #0      PaymentFailureResponse.fromMap (package:razorpay_flutter/razorpay_flutter.dart:151:44)
E/flutter (19060): #1      Razorpay._handleResult (package:razorpay_flutter/razorpay_flutter.dart:72:42)
E/flutter (19060): #2      Razorpay.open (package:razorpay_flutter/razorpay_flutter.dart:54:5)
E/flutter (19060): <asynchronous suspension>
E/flutter (19060):
